### PR TITLE
Update find-container.sh

### PR DESCRIPTION
**Pull request by DerFips**
Changing way how to get ID of running Nextcloud container.

### CODE REVIEW

**Comment by rcdailey** [comment]
Your changes break Docker Compose support. Can you explain what problem you are trying to solve?

**Comment by DerFips** [comment]
I had the problem that I didn't use docker compose but I pulled the image. And it doesn't work on my instance with Containername_containername. I had to shrink it down to just Containername. But yeah, maybe it's working with compose differently. Sorry for that.

**Comment by rcdailey** [comment]
If you aren't using compose, just specify `NEXTCLOUD_CONTAINER_NAME` and leave the project name blank. The documentation explains how to set things up if you're just using docker without compose. Let me know if this gets you what you need.

**Comment by rcdailey** [comment]
@DerFips I'm going to close this PR. Please see my last comment. If that solution doesn't work for you we can reopen. Thanks again for your contribution.

**Pull request closed without merging**
